src/app/urls.py
from django.conf.urls import url

app_name = 'fitapp'

src/signup/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'auth'
urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^register/', views.register, name='register'),
    url(r'^$', auth_views.LoginView.as_view(template_name='signup/cover.html', redirect_field_name='home'),
        name="login")
]

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta http-equiv="Content-Language" content="en"/>
  <meta name="msapplication-TileColor" content="#2d89ef">
  <meta name="theme-color" content="#4188c9">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <title>FitSecret | Help you keep fit</title>
  <!-- Load tabler-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css"
        integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
  <!-- Dashboard Core -->
  <link href="{% static 'assets/css/dashboard.css' %}" rel="stylesheet"/>
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/pikachu (1).png' %}" />
</head>
<body>
{% block content %}
{% endblock %}
{% csrf_token %}
<script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/js/Chart.bundle.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/randomcolor/0.5.2/randomColor.min.js"></script>
{% block script %}
{% endblock %}
</body>
</html>

src/templates/footer.html
<footer class="footer">
  <div class="container">
    <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
      Copyright © 2018 <a href=".">FitSecret</a>. Theme by <a href="https://codecalm.net"
                                                              target="_blank">codecalm.net</a> All rights reserved.
    </div>
  </div>

</footer>

src/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="page">
    <div class="page-main">
      {% include 'nav.html' %}
      <div class="my-3 my-md-5">
        <div class="container">
          <div class="page-header">
            <h1 class="page-title">💪(•ʚ•💪)</h1>
          </div>
          <div class="row">
            <div class="col-6 col-lg-3">
              <div class="card">
                <div class="card-body p-3 text-center">
                  <div class="h1 m-0">{{ food_calories }} kcal</div>
                  <div class="text-muted mb-2">Food</div>
                </div>
              </div>
            </div>
            <div class="col-6 col-lg-3">
              <div class="card">
                <div class="card-body p-3 text-center">
                  <div class="h1 m-0">{{ activities_calories }} kcal</div>
                  <div class="text-muted mb-2">Activities</div>
                </div>
              </div>
            </div>
            <div class="col-6 col-lg-3">
              <div class="card">
                <div class="card-body p-3 text-center">
                  <div class="h1 m-0">{{ current_weight }} kg</div>
                  <div class="text-muted mb-2">Weight</div>
                </div>
              </div>
            </div>
            <div class="col-6 col-lg-3">
              <div class="card">
                <div class="card-body p-3 text-center">
                  <div class="h1 m-0">{{ goal_weight }} kg</div>
                  <div class="text-muted mb-2">Goal</div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12 col-md-6">
              <canvas id="myChart1"></canvas>
            </div>
            <div class="col-sm-12 col-md-6">
              <canvas id="myChart2"></canvas>
            </div>
          </div>
        </div>
      </div>
      {% include 'footer.html' %}
    </div>
  </div>
{% endblock %}
{% block script %}
  <script>
      const ctx1 = document.getElementById("myChart1");
      const ctx2 = document.getElementById("myChart2");
      foodRecordTime = [];
      activitiesRecordTime = [];
      {{ food_item_label }}.forEach(function(label){
          foodRecordTime.push(new Date(label).toDateString())
      });
      {{ activities_item_label }}.forEach(function(label){
          activitiesRecordTime.push(new Date(label).toDateString())
      });
      console.log(foodRecordTime);
      const myChart1 = new Chart(ctx1, {
          type: 'line',
          data: {
              labels:foodRecordTime,
              datasets: [{
                  label: 'Food',
                  data: {{ food_record_data }},
                  backgroundColor: 'rgba(255, 0, 0, 0.5)',
                  fill:false
              }]
          },
          options: {
              scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero: true
                      }
                  }]
              },
              responsive:true,
              title: {
                  display: true,
                  text: 'Recent Food Records'
              }

          }
      });
      const myChart2 = new Chart(ctx2, {
          type: 'line',
          data: {
              labels: activitiesRecordTime,
              datasets: [{
                  label: 'Activities',
                  data: {{ activities_record_data }},
                  backgroundColor: 'rgba(0, 0, 255, 0.5)',
                  fill:false
              }]
          },
          options: {
              scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero: true
                      }
                  }]
              },
              responsive:true,
              title: {
                  display: true,
                  text: 'Recent Activities Records'
              }

          }
      });
  </script>
{% endblock %}

src/templates/nav.html
{% load static %}
<div class="header py-4">
  <div class="container">
    <div class="d-flex">
      <a class="header-brand" href="{% url 'auth:home' %}">
        <img src="{% static 'assets/images/pikachu.svg' %}" class="header-brand-img" alt="logo">FitSecret
      </a>
      <div class="d-flex order-lg-2 ml-auto">
        <div class="dropdown">
          <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
            <span class="avatar" style="background-image: url(https://lh3.googleusercontent.com/-EZnfGPvftkI/AAAAAAAAAAI/AAAAAAAAA5I/in5JbhZ3bp8/s120-p-rw-no/photo.jpg)"></span>
            <span class="ml-2 d-none d-lg-block">
                      <span class="text-default">{{ username }}</span>
                      <small class="text-muted d-block mt-1">Welcome</small>
                    </span>
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
            <a class="dropdown-item" href="#">
              <i class="dropdown-icon fe fe-user"></i> Profile
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'auth:logout' %}">
              <i class="dropdown-icon fe fe-log-out"></i> Sign out
            </a>
          </div>
        </div>
      </div>
      <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse"
         data-target="#headerMenuCollapse">
        <span class="header-toggler-icon"></span>
      </a>
    </div>
  </div>
</div>
<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-3 ml-auto">
        <form class="input-icon my-3 my-lg-0" action="{% url 'search' %}">
          <input type="text" class="form-control header-search" placeholder="Search&hellip;" tabindex="1" name="food">
          <div class="input-icon-addon">
            <i class="fe fe-search"></i>
          </div>
        </form>
      </div>
      <div class="col-lg order-lg-first">
        <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
          <li class="nav-item">
            <a href="{% url 'auth:home' %}" class="nav-link"><i class="fe fe-home"></i>Home</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'food_diary' %}" class="nav-link"><i class="fe fe-calendar"></i>Food dairy</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'activity' %}" class="nav-link"><i class="fa fa-futbol"></i>
              Activities</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="my-3 my-md-5">
</div>