src/app/urls.py
from django.conf.urls import url

app_name = 'fitapp'

src/signup/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'auth'
urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^register/', views.register, name='register'),
    url(r'^$', auth_views.LoginView.as_view(template_name='signup/cover.html', redirect_field_name='home'),
        name="login")
]

src/signup/models.py
import os

from django.contrib.auth.models import User
from django.db import models

from app.fatsecret import Fatsecret


class ProfileManager(models.Manager):
    def create_profile(self, user, current_weight, current_height, goal_weight):
        fs = Fatsecret(os.environ.get('API_KEY'), os.environ.get('API_SECRET'))
        session_token = fs.profile_create()
        fs = Fatsecret(os.environ.get('API_KEY'),
                       os.environ.get('API_SECRET'), session_token)
        fs.weight_update(current_weight_kg=current_weight,
                         goal_weight_kg=current_height, current_height_cm=goal_weight)
        profile = self.create(user=user,
                              auth_token=session_token[0],
                              auth_secret=session_token[1],
                              current_weight=current_weight,
                              current_height=current_height,
                              goal_weight=goal_weight
                              )
        return profile


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    create_date = models.DateField(auto_now_add=True)
    auth_token = models.CharField(max_length=50, null=True, blank=True)
    auth_secret = models.CharField(max_length=50, null=True, blank=True)
    current_weight = models.IntegerField(null=True, blank=True)
    current_height = models.IntegerField(null=True, blank=True)
    goal_weight = models.IntegerField(null=True, blank=True)
    objects = ProfileManager()

    class Meta:
        db_table = 'auth_profile'
        app_label = 'signup'

    def __str__(self):
        return self.user.get_username()

    def get_session_token(self):
        if self.auth_token and self.auth_secret:
            return [self.auth_token, self.auth_secret]
        else:
            return None

    def get_current_weight(self):
        return self.current_weight

    def get_current_height(self):
        return self.current_height

    def get_goal_weight(self):
        return self.goal_weight

src/signup/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.utils.translation import gettext as _


def forbidden_username_validator(value):
    forbidden_usernames = ['admin', 'settings', 'news', 'about', 'help',
                           'signin', 'signup', 'signout', 'terms', 'privacy',
                           'cookie', 'new', 'login', 'logout', 'administrator',
                           'join', 'account', 'username', 'root', 'blog',
                           'user', 'users', 'billing', 'subscribe', 'reviews',
                           'review', 'blog', 'blogs', 'edit', 'mail', 'email',
                           'home', 'job', 'jobs', 'contribute', 'newsletter',
                           'shop', 'profile', 'register', 'auth',
                           'authentication', 'campaign', 'config', 'delete',
                           'remove', 'forum', 'forums', 'download',
                           'downloads', 'contact', 'blogs', 'feed', 'feeds',
                           'faq', 'intranet', 'log', 'registration', 'search',
                           'explore', 'rss', 'support', 'status', 'static',
                           'media', 'setting', 'css', 'js', 'follow',
                           'activity', 'questions', 'articles', 'network', ]

    if value.lower() in forbidden_usernames:
        raise ValidationError(
            _('This is a reserved word.'), code='name_forbid')


def invalid_username_validator(value):
    if '@' in value or '+' in value or '-' in value:
        raise ValidationError(
            _('Enter a valid username.'),  code='name_invalid',)


def unique_email_validator(value):
    if User.objects.filter(email__iexact=value).exists():
        raise ValidationError(
            _('User with this Email already exists.'), code='email_exists')


def unique_username_ignore_case_validator(value):
    if User.objects.filter(username__iexact=value).exists():
        raise ValidationError(
            _('User with this Username already exists.'), code='name_exists')


class SignUpForm(forms.ModelForm):
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=30,
        required=True,
        validators=[forbidden_username_validator,
                    invalid_username_validator, unique_username_ignore_case_validator]
    )
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Confirm your password",
        required=True)
    email = forms.CharField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        required=True,
        max_length=75,
        validators=[unique_email_validator, validate_email])
    current_weight = forms.IntegerField(
        label='Current weight(kg)',
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
        required=True,
        min_value=40,
        max_value=300)
    current_height = forms.IntegerField(
        label='Current height(cm)',
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
        required=True,
        min_value=100,
        max_value=250)
    goal_weight = forms.IntegerField(
        label='Goal weight(kg)',
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
        required=True,
        min_value=40,
        max_value=300)

    class Meta:
        model = User
        exclude = ['last_login', 'date_joined']
        fields = ['username', 'email', 'password', 'confirm_password', ]

    def clean(self):
        super(SignUpForm, self).clean()
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password and password != confirm_password:
            message = 'Passwords don\'t match'
            self.add_error('password', message)
        return self.cleaned_data

src/signup/views.py
import os
from datetime import datetime

from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

from app.fatsecret import Fatsecret

from .forms import SignUpForm
from .models import Profile


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if not form.is_valid():
            return render(request, 'signup/register.html', {'form': SignUpForm(), 'errors': form.errors})
        else:
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            current_weight = form.cleaned_data.get('current_weight')
            current_height = form.cleaned_data.get('current_height')
            goal_weight = form.cleaned_data.get('goal_weight')
            new_user = User.objects.create_user(
                username=username, password=password, email=email)
            Profile.objects.create_profile(
                new_user, current_weight, current_height, goal_weight)
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/home')
    else:
        return render(request, 'signup/register.html', {'form': SignUpForm()})


def home(request):
    if request.user.is_authenticated():
        current_profile = Profile.objects.get(user=request.user)
        current_weight = current_profile.get_current_weight()
        goal_weight = current_profile.get_goal_weight()
        fs = Fatsecret(os.environ.get('API_KEY'), os.environ.get(
            'API_SECRET'), current_profile.get_session_token())
        fs.exercise_entries_commit_day()
        food_record = fs.food_entries_get_month()
        food_record_data = []
        food_item_label = []
        food_calories = 0
        if food_record is not None:
            for item in food_record:
                food_record_data.append(int(item['calories']))
                food_calories = food_calories + int(item['calories'])
                food_item_label.append(int(item['date_int'])*24*60*60*1000)

        activities_record = fs.exercise_entries_get_month()
        activities_calories = 0
        activities_record_data = []
        activities_item_label = []
        if activities_record is not None:
            for item in activities_record:
                activities_record_data.append(int(item['calories']))
                if fs.unix_time(datetime.now()) == int(item['date_int']):
                    activities_calories = int(item['calories'])
                activities_item_label.append(
                    int(item['date_int'])*24*60*60*1000)

        context = {'food_calories': food_calories,
                   'activities_calories': activities_calories,
                   'current_weight': current_weight,
                   'goal_weight': goal_weight,
                   'username': request.user.get_username(),
                   'food_record_data': food_record_data,
                   'food_item_label': food_item_label,
                   'activities_record_data': activities_record_data,
                   'activities_item_label': activities_item_label
                   }
        return render(request, 'home.html', context)
    else:
        return redirect('/')

src/signup/templates/signup/cover.html
{% extends 'base.html' %}
{% block content %}
  <div class="page">
    <div class="page-single">
      <div class="container">
        <div class="row">
          {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
              <div class="col col-login mx-auto alert alert-danger alert-dismissable">
                {{ error }}
              </div>
            {% endfor %}
          {% endif %}
        </div>
        <div class="row">
          <div class="col col-login mx-auto">
            <div class="text-center mb-6">
              <!--logo -->
            </div>
            <form class="card" action="{% url 'auth:login' %}" method="post">
              {% csrf_token %}
              <div class="card-body p-6">
                <div class="card-title">Login to your account</div>
                <div class="form-group {% if form.username.errors %} has-error{% endif %}">
                  <label class="form-label">Username:</label>
                  <input type="text" class="form-control" name="username" id="id_username"
                         placeholder="Enter username">
                </div>
                <div class="form-group {% if form.username.errors %} has-error{% endif %}">
                <label class="form-label">Password:</label>
                  <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
                </div>
                <div class="form-footer">
                  <button type="submit" class="btn btn-primary btn-block">Sign in</button>
                </div>
              </div>
            </form>
            <div class="text-center text-muted">
              Don't have account yet? <a href="{% url 'auth:register' %}"> Sign up</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

src/signup/templates/signup/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div id="particles-js">
      <div class="container">
      <div class="row">
          {% if errors %}
              <div class="col col-login mx-auto alert alert-danger alert-dismissable">
                {{ errors }}
              </div>
          {% endif %}
        </div>
        <div class="row">
          <div class="col col-login mx-auto">
            <div class="text-center mb-6">
            </div>
            <form class="card" action="{% url 'auth:register' %}" method="post">
              {% csrf_token %}
              <div class="card-body p-6">
                <div class="card-title">Create new account</div>
                {% for field in form.visible_fields %}
                  <div class="form-group{% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.help_text %}
                      <span class="help-block">{{ field.help_text|safe }}</span>
                    {% endif %}
                    {% endfor %}
                  </div>
                <div class="form-footer">
                  <button type="submit" class="btn btn-primary btn-block">Create new account</button>
                </div>
              </div>
            </form>
            <div class="text-center text-muted">
              <!-- Social login -->
            </div>
          </div>
        </div>
      </div>
  </div>
{% endblock %}